### ISSUE TITLE
Add OpenCL support

### ISSUE THREAD

**Issue by arporter** [stfc/dl_esm_inf#10]
For EuroEXA we want to build models that use OpenCL. We have a manual version of nemolite2d in PSycloneBench already. In this issue we will take the code developed there and make it part of this library. This will then enable PSyclone-generated code to target OpenCL.

**Comment by arporter** [comment]
Code is now compiling. Run successfully loads kernel objects but then seg. faults because at no point do I set-up the fields on the device! In the single file version I did this in nemolite2d.f90 for pointers that I declared there. However, now I want to set-up `field%device_ptr`.

**Comment by arporter** [comment]
In contrast to the title of this issue, I've removed all dependence on FortCL now. However, I'm keeping the extra field/grid-property pointers for device memory. If the calling application wants to use OpenCL the it is up to it to use FortCL.

**Comment by arporter** [comment]
On discussion with @rupertford, particularly under https://github.com/stfc/PSycloneBench/pull/15, we've agreed that it should be the responsibility of the infrastructure to deal with any data movement, not the application. We do therefore need to make the infrastructure 'OpenCL-aware'.

**Comment by arporter** [comment]
If I add a getter method and make the `data` member of the field object private then that breaks a lot of code. A halfway house would be to implement the getter method but leave the `data` member public so that we can gradually move code across. Simpler still would be to move IO functionality out of PSycloneBench and into here where we can handle any data-movement issues. The 'right' answer depends on how we view dl_esm_inf. Is it a test-bed/prototyping code or do we envisage replacing it altogether with e.g. Atlas?

Having written all that, I'm thinking I should add the getter method, leave `data` public and then alter the IO routines to use the getter method. Comments @rupertford, @hiker?

**Comment by arporter** [comment]
@sergisiso is this Issue still live?

**Comment by sergisiso** [comment]
No, I would say OpenCL is already supported :) So I am closing the issue.
