### ISSUE TITLE
kernel_type or go_kernel_type?

### ISSUE THREAD

**Issue by hiker** [stfc/dl_esm_inf#12]
I just realised that kernel_mod.F90 still contains:
```
type :: kernel_type
  private
  logical :: no_op

end type kernel_type
```

Should that be go_kernel_type? Note that this requires a few changes in PSyclone (especially test files for compilation) then :(

**Comment by arporter** [comment]
TBH, I think that now that we've fixed the big problem of having `READ` and `WRITE` as keywords in the meta-data we can hold off worrying about this. Especially if it requires quite a few changes... :-)

**Comment by hiker** [comment]
Fair enough :)  I need another pull request since I ran into a few compile and runtime issues, but that will be a separate issue then.

**Comment by hiker** [comment]
Fair enough :)  I need another pull request since I ran into a few compile and runtime issues, but that will be a separate issue then.
