### ISSUE TITLE
Names of quantities clash with Fortran instrinsic types/routines

### ISSUE THREAD

**Issue by arporter** [stfc/dl_esm_inf#3]
In dropping the "GH_" prefix used when naming constants in the LFRic infrastructure, I've ended up with a lot of names that clash with Fortran intrinsics. This is bad. It also means that Omni won't compile the code.

We will choose a suitable prefix and apply it.

**Comment by arporter** [comment]
@hiker did you say you already had a branch where you'd fixed this? Alternatively I can do it.

**Comment by hiker** [comment]
Me?? No, I don't think I have anything to do with this.

**Comment by arporter** [comment]
Code now compiles with Omni. (Issue was actually to do with some weirdness where we declared various integers with kind parameters declared in an enumeration. I couldn't see any point to that so have made them just default integers.)

**Comment by arporter** [comment]
PR has been merged, closing issue.
