### ISSUE TITLE
MPI and accelerator devices support combined

### ISSUE THREAD

**Issue by sergisiso** [stfc/dl_esm_inf#30]
At the moment the Makefile has a target with MPI=yes  and a target with OCL=yes, but there is no target to both (MPI=yes OCL=yes) at the same time.

I would be great to have support for both, this requires updating the Makefile and checking that the code could supports both programming models at the same time.

**Comment by arporter** [comment]
Thanks to the work done by @sergisiso in decoupling the infrastructure from OpenCL, the Makefile no longer has an OCL option in it. Presumably that means we can close this issue as it will "just work"?

**Comment by sergisiso** [comment]
This issue now would be that any potentially distributed-memory method like `field%halo_exchange` or `field%array_checksum` do retrieve first the data from the device (with the field%get_data()) if the host does not have the latest version. I know halo_exchanges do that but I am not sure this is consistent throughout the code.

Since I want to attempt the MPI+OpenCL in NemoLite2D sometime soon I propose just renaming it for now until we can verify it does work.

**Comment by sergisiso** [comment]
This has been proven to work in NemoLite2D. Closing issue.
