### ISSUE TITLE
field_copy is broken

### ISSUE THREAD

**Issue by arporter** [stfc/dl_esm_inf#36]
In debugging the fact that the manual, distributed-memory version of nemolite2d doesn't work, I've found that this is because the field_copy routine is broken.

**Comment by arporter** [comment]
The problem was that copy_field() was written so as to be parallelised over tiles but the tile bounds were not being set correctly. Since we don't use tiling anyway, I've turned off the creation of the tiles and altered the routine so that it first checks whether a field is tiled.

**Comment by sergisiso** [comment]
Fixed with PR #37
