### ISSUE TITLE
Make the ALIGNMENT parameter configurable

### ISSUE THREAD

**Issue by sergisiso** [stfc/dl_esm_inf#45]
Currently ALIGNMENT is a Fortran parameter defined in two files in 2 files: 'grid_mod.f90' and 'global_parameters_mod.f90' and is set to 4 (256-bits alignment for doubles). This parameter adds padding to the nx dimension so that any row(contiguous dimension) starts in a aligned position.

It would be useful to make this parameter configurable for different vector sizes, but also to add padding for other reasons (e.g. make the OpenCL with local_size work with arbitrary problem sizes).

This needs to be done before the grid_init() which computes the nx and ny sizes, but since this is a performance specific parameter it is not clear what the best interface is in order to not pollute the algorithm description.

**Comment by arporter** [comment]
We could pick up the value from an environment variable?

**Comment by sergisiso** [comment]
Yes, that could be a good option

**Comment by sergisiso** [comment]
Alignment can now be specified with the DL_ESM_ALIGNMENT environment variable. Closing this issue.
