### ISSUE TITLE
Crash with intel compiler when no tmask is specified.

### ISSUE THREAD

**Issue by hiker** [stfc/dl_esm_inf#57]
Not sure about the standard, but Intel 20 crashes when no ``tmask`` is given to the ``grid_init``:
```
  subroutine grid_init(grid, dxarg, dyarg, tmask)
    integer, allocatable, dimension(:,:), intent(in), optional :: tmask
...
    call map_comms(grid%decomp, tmask, .false., (/1,1/), ierr(1))
```
If  ``tmask`` is not specified, the code crashes when adding tmask in the call to map_comms. As a quick work around I used:
```
diff --git a/finite_difference/src/grid_mod.f90 b/finite_difference/src/grid_mod.f90
index 155c636..363fb5e 100644
--- a/finite_difference/src/grid_mod.f90
+++ b/finite_difference/src/grid_mod.f90
@@ -518,7 +518,7 @@ contains
                    &  //'periodic boundary conditions.')
     end if
     
-    call map_comms(grid%decomp, tmask, .false., (/1,1/), ierr(1))
+    call map_comms(grid%decomp, grid%tmask, .false., (/1,1/), ierr(1))
 
     if(ierr(1) /= 0)call gocean_stop('Set-up of communication tables (call ' &
                                  & //'to map_comms()) failed.')
```
So I pass the ``tmask`` field of the grid object - which works even if it is not allocated.

**Comment by arporter** [comment]
Oh yes, that looks wrong. I've just looked at the code and have realised that tmask can only be skipped if there are periodic boundary conditions and we don't yet support those with distributed memory. This is the subject of #54. My only concern with the proposed fix is what happens if `map_comms` is called with an unallocated tmask and a processor grid that is not 1x1. In theory this should never happen but better to put some defensive checks in `map_comms` I think.

**Comment by hiker** [comment]
As far as I can see, ``tmask`` is not used at all in ``map_comms``. It is passed to ``addsend`` and ``addrecv`` calls, but they in turn do not use ``tmask`` at all. I don't know if this because there is still work happening that might need ``tmask`` later - but so far it would appear that just removing ``tmask`` from ``map_comms`` would be the best and easiest solution.

**Comment by arporter** [comment]
I think it's a hangover from the code from which the halo-exchange stuff was derived - it was clever and used the Tmask to identify land points which therefore didn't need to be halo exchanged. It seems unlikely that we'll ever need this level of sophistication in dl_esm_inf but, if we keep the tmask argument in the top-level API then at least we wouldn't need an API change to introduce it?
