### ISSUE TITLE
Simple MPI support

### ISSUE THREAD

**Issue by hiker** [stfc/dl_esm_inf#64]
For the PSyclone training material, I want to provide very easy distributed memory support. This requires three changes:
- [ ] Allow fields to be constructed with a global field: the global field will be distributed to each domain and used to initialise a field.
- [ ] Provide functionality to gather a distributed field back to a 2d-Fortran array. This will allow to use unmodified IO (though of course not being very efficient)
- [ ] At this stage the grid grid expects a T-MASK if non-periodic boundaries are used. There seems to be no real reason for this, as far as I can see the code otherwise works fine without a T-MASK.

**Comment by arporter** [comment]
@hiker, can this be closed now that #65 is on?

**Comment by hiker** [comment]
Thanks for merging!!
